// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in example/ent/runtime.go

const (
	Version = "v0.8.1-0.20210425155435-43e74a334fdf"            // Version of ent codegen.
	Sum     = "h1:17sFV65gM98kuNMTL1z8+UWlBXkSqSqzGIAjlWpCVhg=" // Sum of ent codegen.
)
